#ifndef CONFIG_H
#define CONFIG_H

#define EMULATOR_WINDOW_TITLE "chip8 Emulator"
#define CHIP8_MEMORY_SIZE 4096
#define CHIP8_DISPLAY_WIDTH 64
#define CHIP8_DISPLAY_HEIGHT 32
#define CHIP8_WINDOW_SCALE 10
#define CHIP8_REGISTERS_COUNT 16
#define CHIP8_STACK_DEPTH 16
#define CHIP8_KEYS_COUNT 16
#define CHIP8_CS_LOAD_ADDRESS 0x00  // character set load address
#define CHIP8_PROGRAM_LOAD_ADDRESS 0x200
#define CHIP8_CS_HEIGHT 5

#endif
